name: CI - Build Python Package

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build Python Package
    runs-on: macos-latest
    env:
      branch: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Python 3 libraries
        run: pip3 install setuptools wheel twine build

      - name: Validate Library (py3)
        run: python3 macos_pkg_builder.py

      - name: Validate setup.py
        run: python3 setup.py check -m -s

      - name: Build Package (py3)
        run: python3 -m build --wheel

      - name: Test Package (py3)
        run: python3 setup.py test

      - name: Validate twine
        run: twine check dist/*

      - name: Test Library Installation (py3)
        run: pip3 install dist/*.whl

      - name: Test Library (py3)
        run: cd /; python3 -c "import macos_pkg_builder; print(macos_pkg_builder.__version__)"

      - name: Upload Wheel Package
        uses: actions/upload-artifact@v2
        with:
          name: macos_pkg_builder.whl
          path: dist/*.whl

      - name: Upload Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true

      - name: Publish PyPI Package
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*